M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-09-14T04:58:20+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-14T04:58:20+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X9.1Y-22.11
X9.1Y-27.89
T2
X4.0Y-4.0
X4.0Y-46.0
X46.0Y-4.0
X46.0Y-46.0
M30
